// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// StatusJumpsHandlerFunc turns a function with the right signature into a status jumps handler
type StatusJumpsHandlerFunc func(StatusJumpsParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn StatusJumpsHandlerFunc) Handle(params StatusJumpsParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// StatusJumpsHandler interface for that can handle valid status jumps params
type StatusJumpsHandler interface {
	Handle(StatusJumpsParams, interface{}) middleware.Responder
}

// NewStatusJumps creates a new http.Handler for the status jumps operation
func NewStatusJumps(ctx *middleware.Context, handler StatusJumpsHandler) *StatusJumps {
	return &StatusJumps{Context: ctx, Handler: handler}
}

/* StatusJumps swagger:route GET /jumps statusJumps

Get the status of all jump connections

Get the status of all jump connections

*/
type StatusJumps struct {
	Context *middleware.Context
	Handler StatusJumpsHandler
}

func (o *StatusJumps) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewStatusJumpsParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
