// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Status
//
//  API for accessing status of experiments
//  Schemes:
//    http
//  Host: localhost
//  BasePath: /
//  Version: 0.0
//  Contact: Timothy Drysdale<timothy.d.drysdale@gmail.com> https://github.com/timdrysdale
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
